# Generated by Django 4.1.4 on 2022-12-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='fro',
            field=models.CharField(default='self', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='to',
            field=models.CharField(max_length=20),
        ),
    ]
